// Mock data para demonstração

import { Investment, MarketTrend, NewsItem, Notification } from '../types';

export const generateMarketTrends = (): MarketTrend[] => {
  const trends: MarketTrend[] = [];
  const baseValue = 10000;
  const days = 30;

  for (let i = 0; i < days; i++) {
    const date = new Date();
    date.setDate(date.getDate() - (days - i));
    const randomChange = (Math.random() - 0.5) * 500;
    const value = baseValue + randomChange + (i * 50);
    
    trends.push({
      date: date.toISOString().split('T')[0],
      value: Math.round(value),
    });
  }

  return trends;
};

export const mockInvestments: Investment[] = [
  // Ações - Tech Giants
  {
    id: '1',
    name: 'Apple Inc.',
    type: 'stocks',
    currentPrice: 178.45,
    change24h: 2.34,
    changePercent: 1.33,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '4',
    name: 'Microsoft Corp.',
    type: 'stocks',
    currentPrice: 412.89,
    change24h: 5.67,
    changePercent: 1.39,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '7',
    name: 'Google (Alphabet)',
    type: 'stocks',
    currentPrice: 142.65,
    change24h: 3.21,
    changePercent: 2.30,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '8',
    name: 'Amazon.com Inc.',
    type: 'stocks',
    currentPrice: 178.35,
    change24h: -2.15,
    changePercent: -1.19,
    recommendation: 'hold',
    riskLevel: 'medium',
  },
  {
    id: '9',
    name: 'Meta Platforms',
    type: 'stocks',
    currentPrice: 487.23,
    change24h: 12.45,
    changePercent: 2.62,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '10',
    name: 'Tesla Inc.',
    type: 'stocks',
    currentPrice: 242.84,
    change24h: -8.34,
    changePercent: -3.32,
    recommendation: 'hold',
    riskLevel: 'high',
  },
  {
    id: '11',
    name: 'NVIDIA Corp.',
    type: 'stocks',
    currentPrice: 875.28,
    change24h: 23.45,
    changePercent: 2.75,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '12',
    name: 'Netflix Inc.',
    type: 'stocks',
    currentPrice: 612.45,
    change24h: 15.67,
    changePercent: 2.63,
    recommendation: 'buy',
    riskLevel: 'medium',
  },

  // Ações - Brasileiras
  {
    id: '13',
    name: 'Petrobras (PETR4)',
    type: 'stocks',
    currentPrice: 38.45,
    change24h: 0.87,
    changePercent: 2.31,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '14',
    name: 'Vale (VALE3)',
    type: 'stocks',
    currentPrice: 62.34,
    change24h: -1.23,
    changePercent: -1.93,
    recommendation: 'hold',
    riskLevel: 'medium',
  },
  {
    id: '15',
    name: 'Itaú Unibanco (ITUB4)',
    type: 'stocks',
    currentPrice: 28.76,
    change24h: 0.45,
    changePercent: 1.59,
    recommendation: 'buy',
    riskLevel: 'low',
  },
  {
    id: '16',
    name: 'Banco do Brasil (BBAS3)',
    type: 'stocks',
    currentPrice: 52.18,
    change24h: 1.12,
    changePercent: 2.19,
    recommendation: 'buy',
    riskLevel: 'low',
  },
  {
    id: '17',
    name: 'Ambev (ABEV3)',
    type: 'stocks',
    currentPrice: 13.45,
    change24h: 0.23,
    changePercent: 1.74,
    recommendation: 'hold',
    riskLevel: 'low',
  },
  {
    id: '18',
    name: 'Magazine Luiza (MGLU3)',
    type: 'stocks',
    currentPrice: 8.92,
    change24h: -0.34,
    changePercent: -3.67,
    recommendation: 'sell',
    riskLevel: 'high',
  },

  // Criptomoedas - Top 20
  {
    id: '2',
    name: 'Bitcoin',
    type: 'crypto',
    currentPrice: 43250.00,
    change24h: -1234.50,
    changePercent: -2.77,
    recommendation: 'hold',
    riskLevel: 'high',
  },
  {
    id: '5',
    name: 'Ethereum',
    type: 'crypto',
    currentPrice: 2345.78,
    change24h: -89.23,
    changePercent: -3.66,
    recommendation: 'sell',
    riskLevel: 'high',
  },
  {
    id: '19',
    name: 'Binance Coin (BNB)',
    type: 'crypto',
    currentPrice: 312.45,
    change24h: 8.67,
    changePercent: 2.85,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '20',
    name: 'Solana',
    type: 'crypto',
    currentPrice: 98.76,
    change24h: 5.43,
    changePercent: 5.82,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '21',
    name: 'Cardano (ADA)',
    type: 'crypto',
    currentPrice: 0.58,
    change24h: 0.02,
    changePercent: 3.57,
    recommendation: 'hold',
    riskLevel: 'high',
  },
  {
    id: '22',
    name: 'Ripple (XRP)',
    type: 'crypto',
    currentPrice: 0.62,
    change24h: -0.03,
    changePercent: -4.62,
    recommendation: 'hold',
    riskLevel: 'high',
  },
  {
    id: '23',
    name: 'Polkadot (DOT)',
    type: 'crypto',
    currentPrice: 7.23,
    change24h: 0.34,
    changePercent: 4.93,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '24',
    name: 'Dogecoin',
    type: 'crypto',
    currentPrice: 0.087,
    change24h: 0.003,
    changePercent: 3.57,
    recommendation: 'hold',
    riskLevel: 'high',
  },
  {
    id: '25',
    name: 'Avalanche (AVAX)',
    type: 'crypto',
    currentPrice: 36.78,
    change24h: 2.15,
    changePercent: 6.21,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '26',
    name: 'Polygon (MATIC)',
    type: 'crypto',
    currentPrice: 0.89,
    change24h: 0.05,
    changePercent: 5.95,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '27',
    name: 'Chainlink (LINK)',
    type: 'crypto',
    currentPrice: 14.56,
    change24h: 0.78,
    changePercent: 5.66,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '28',
    name: 'Litecoin',
    type: 'crypto',
    currentPrice: 72.34,
    change24h: -2.45,
    changePercent: -3.28,
    recommendation: 'hold',
    riskLevel: 'high',
  },
  {
    id: '29',
    name: 'Uniswap (UNI)',
    type: 'crypto',
    currentPrice: 6.78,
    change24h: 0.34,
    changePercent: 5.28,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '30',
    name: 'Cosmos (ATOM)',
    type: 'crypto',
    currentPrice: 9.87,
    change24h: 0.56,
    changePercent: 6.01,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '31',
    name: 'Stellar (XLM)',
    type: 'crypto',
    currentPrice: 0.12,
    change24h: 0.01,
    changePercent: 9.09,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '32',
    name: 'VeChain (VET)',
    type: 'crypto',
    currentPrice: 0.028,
    change24h: 0.002,
    changePercent: 7.69,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '33',
    name: 'Algorand (ALGO)',
    type: 'crypto',
    currentPrice: 0.18,
    change24h: 0.01,
    changePercent: 5.88,
    recommendation: 'hold',
    riskLevel: 'high',
  },
  {
    id: '34',
    name: 'Tron (TRX)',
    type: 'crypto',
    currentPrice: 0.11,
    change24h: 0.005,
    changePercent: 4.76,
    recommendation: 'hold',
    riskLevel: 'high',
  },
  {
    id: '35',
    name: 'Tezos (XTZ)',
    type: 'crypto',
    currentPrice: 1.02,
    change24h: 0.06,
    changePercent: 6.25,
    recommendation: 'buy',
    riskLevel: 'high',
  },
  {
    id: '36',
    name: 'Monero (XMR)',
    type: 'crypto',
    currentPrice: 158.45,
    change24h: -5.67,
    changePercent: -3.45,
    recommendation: 'hold',
    riskLevel: 'high',
  },

  // Títulos e Renda Fixa
  {
    id: '3',
    name: 'Tesouro Direto IPCA+',
    type: 'bonds',
    currentPrice: 3245.67,
    change24h: 12.34,
    changePercent: 0.38,
    recommendation: 'buy',
    riskLevel: 'low',
  },
  {
    id: '37',
    name: 'Tesouro Selic 2027',
    type: 'bonds',
    currentPrice: 11234.56,
    change24h: 8.90,
    changePercent: 0.08,
    recommendation: 'buy',
    riskLevel: 'low',
  },
  {
    id: '38',
    name: 'CDB Banco Inter 120% CDI',
    type: 'bonds',
    currentPrice: 10500.00,
    change24h: 15.00,
    changePercent: 0.14,
    recommendation: 'buy',
    riskLevel: 'low',
  },
  {
    id: '39',
    name: 'LCI Itaú 95% CDI',
    type: 'bonds',
    currentPrice: 9800.00,
    change24h: 12.00,
    changePercent: 0.12,
    recommendation: 'hold',
    riskLevel: 'low',
  },
  {
    id: '40',
    name: 'Debênture Petrobras 2028',
    type: 'bonds',
    currentPrice: 1045.67,
    change24h: 3.45,
    changePercent: 0.33,
    recommendation: 'buy',
    riskLevel: 'medium',
  },

  // Fundos Imobiliários
  {
    id: '6',
    name: 'Fundo Imobiliário HGLG11',
    type: 'funds',
    currentPrice: 165.43,
    change24h: 1.23,
    changePercent: 0.75,
    recommendation: 'hold',
    riskLevel: 'medium',
  },
  {
    id: '41',
    name: 'MXRF11 - Maxi Renda',
    type: 'funds',
    currentPrice: 10.45,
    change24h: 0.08,
    changePercent: 0.77,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '42',
    name: 'KNRI11 - Kinea Renda',
    type: 'funds',
    currentPrice: 142.78,
    change24h: 1.56,
    changePercent: 1.10,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '43',
    name: 'VISC11 - Vinci Shopping',
    type: 'funds',
    currentPrice: 98.34,
    change24h: 0.67,
    changePercent: 0.69,
    recommendation: 'hold',
    riskLevel: 'medium',
  },
  {
    id: '44',
    name: 'XPML11 - XP Malls',
    type: 'funds',
    currentPrice: 112.56,
    change24h: 1.23,
    changePercent: 1.10,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '45',
    name: 'BTLG11 - BTG Logística',
    type: 'funds',
    currentPrice: 105.89,
    change24h: 0.89,
    changePercent: 0.85,
    recommendation: 'buy',
    riskLevel: 'medium',
  },

  // Ações Internacionais
  {
    id: '46',
    name: 'Coca-Cola Co.',
    type: 'stocks',
    currentPrice: 59.87,
    change24h: 0.45,
    changePercent: 0.76,
    recommendation: 'hold',
    riskLevel: 'low',
  },
  {
    id: '47',
    name: 'Johnson & Johnson',
    type: 'stocks',
    currentPrice: 156.34,
    change24h: 1.23,
    changePercent: 0.79,
    recommendation: 'buy',
    riskLevel: 'low',
  },
  {
    id: '48',
    name: 'Visa Inc.',
    type: 'stocks',
    currentPrice: 267.45,
    change24h: 3.67,
    changePercent: 1.39,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '49',
    name: 'Mastercard Inc.',
    type: 'stocks',
    currentPrice: 412.78,
    change24h: 5.23,
    changePercent: 1.28,
    recommendation: 'buy',
    riskLevel: 'medium',
  },
  {
    id: '50',
    name: 'Walt Disney Co.',
    type: 'stocks',
    currentPrice: 92.34,
    change24h: -1.45,
    changePercent: -1.55,
    recommendation: 'hold',
    riskLevel: 'medium',
  },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'Fed mantém taxa de juros estável',
    summary: 'Banco Central dos EUA decide manter taxa de juros entre 5,25% e 5,50%, sinalizando possível corte no próximo trimestre.',
    source: 'Reuters',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    impact: 'positive',
  },
  {
    id: '2',
    title: 'Tech stocks sobem após resultados positivos',
    summary: 'Ações de tecnologia registram alta generalizada após divulgação de balanços acima das expectativas do mercado.',
    source: 'Bloomberg',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    impact: 'positive',
  },
  {
    id: '3',
    title: 'Petróleo cai com aumento de produção',
    summary: 'Preços do petróleo recuam 3% após OPEC+ anunciar aumento na produção para o próximo trimestre.',
    source: 'Financial Times',
    timestamp: new Date(Date.now() - 10800000).toISOString(),
    impact: 'negative',
  },
  {
    id: '4',
    title: 'Inflação mostra sinais de desaceleração',
    summary: 'Índices de inflação apresentam queda pelo terceiro mês consecutivo, reforçando expectativas de corte de juros.',
    source: 'Wall Street Journal',
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    impact: 'positive',
  },
];

export const generateNotifications = (): Notification[] => {
  return [
    {
      id: '1',
      type: 'opportunity',
      title: 'Oportunidade de Compra',
      message: 'Apple Inc. atingiu preço-alvo de compra. Considere adicionar à carteira.',
      timestamp: new Date(Date.now() - 1800000).toISOString(),
      read: false,
    },
    {
      id: '2',
      type: 'alert',
      title: 'Alerta de Volatilidade',
      message: 'Bitcoin apresenta alta volatilidade. Monitore sua posição.',
      timestamp: new Date(Date.now() - 5400000).toISOString(),
      read: false,
    },
    {
      id: '3',
      type: 'warning',
      title: 'Rebalanceamento Sugerido',
      message: 'Sua carteira está desbalanceada. Considere ajustar alocação.',
      timestamp: new Date(Date.now() - 9000000).toISOString(),
      read: true,
    },
  ];
};
